{% set name = "tsplib95" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tsplib95-{{ version }}.tar.gz
  sha256: 3da80175dfb0478b967b87c508f75def47371188b6401b719441f2cedc817e00

build:
  entry_points:
    - tsplib95=tsplib95.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
  run:
    - python >={{ python_min }}
    - click >=6.0
    - deprecated >=1.2.9
    - networkx >=2.1
    - tabulate >=0.8.7

test:
  imports:
    - tsplib95
  commands:
    - tsplib95 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rhgrant10/tsplib95
  summary: TSPLIB95 works with TSPLIB95 files.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moorepants
